# Generated by Django 4.1.2 on 2022-11-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=50)),
                ('Tage', models.IntegerField()),
                ('Tphone', models.BigIntegerField()),
                ('Temail', models.EmailField(max_length=50)),
                ('Tpassword', models.CharField(max_length=50)),
                ('Tcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_app.city')),
                ('Tcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_No', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Trainer_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_app.course')),
                ('Trainer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_app.trainer_reg')),
            ],
        ),
    ]
